#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpx --no-install lint-staged
if exec < /dev/tty; then ts-node src/index.ts check; fi # !Important! Ensures that the script is not run in the background, so stdin is available.
pre-commit